Integrate subgraph repo to htm_escrow
humanprotocol/hmt-escrow pull request #337
Opened 2022-06-23 18:27 UTC by Charlie85270

This PR fix : 

- https://github.com/humanprotocol/hmt-escrow/issues/333
- https://github.com/humanprotocol/humansubgraph/issues/16
- https://github.com/humanprotocol/humansubgraph/issues/7

2022-06-23 18:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/humanprotocol/hmt-escrow?pullRequest=337) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/humanprotocol/hmt-escrow?pullRequest=337) before we can accept your contribution.<br/><hr/>**Charlie Rabiller** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/humanprotocol/hmt-escrow?pullRequest=337) it.</sub>

2022-06-23 19:02 UTC, posix4e commented
@ivhus @Dzeranov he already signed nda on another repo so no worries

2022-06-24 17:16 UTC, ivhus commented
`.github` part looks fine to me, idk much about internals of other specific parts though. CI+CD approved

2022-06-24 17:16 UTC, ivhus approved these changes

2022-06-24 19:46 UTC, ivhus reviewed
binaries and temporary files like .DS_Store shouldn't be included in version control and also those are better to add to .gitignore @Charlie85270

2022-06-25 00:20 UTC, Charlie85270 commented
Updated

2022-06-25 00:33 UTC, posix4e requested changes
There’s no need to check in the Abi. It should be generated

2022-06-25 00:38 UTC, Charlie85270 commented
> There’s no need to check in the Abi. It should be generated

What do you mean by check ? versioned ? 

There are automatically generated before run/build the subgraph

2022-06-25 00:50 UTC, posix4e requested changes

2022-06-25 00:50 UTC, posix4e commented on hmt_subgraph/abis/EscrowFactory.json
> +[
Don’t check this in

2022-06-25 00:50 UTC, posix4e commented on hmt_subgraph/abis/Escrow.json
> +[
Don’t check this in

2022-06-25 00:51 UTC, posix4e approved these changes

2022-06-25 00:51 UTC, Charlie85270 commented
Updated, I removed the generated ABI files.

2022-06-25 16:25 UTC, merged